//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by eBUSPlayer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_EBUSPLAYER_DIALOG           102
#define IDD_EBUSPLAYER                  102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDR_MENU                        130
#define IDR_HTML1                       132
#define IDD_EVENTMONITOR                133
#define IDB_PLAY                        134
#define IDB_STOP                        135
#define IDD_OPENSTREAM                  136
#define IDR_ACCELERATOR                 140
#define IDD_SETUP                       141
#define IDD_FILTERING                   142
#define IDD_IMAGE_SAVE_OPTIONS          143
#define IDD_REGISTERINTERFACE           144
#define IDD_BUFFER_OPTIONS              146
#define IDD_ABOUTBOX                    147
#define IDD_SPLASHPAGE                  148
#define IDB_ABOUT                       149
#define IDB_SPLASH                      150
#define IDD_DIALOG1                     151
#define IDD_NO_DRIVER                   151
#define IDD_ERRORS                      152
#define IDD_ACTIONCOMMAND               154
#define IDD_FILETRANSFER                155
#define IDD_HISTOGRAM                   157
#define IDD_HISTOGRAMCTRL               157
#define IDC_CONNECT_SELECT              1000
#define IDC_CONNECT_BUTTON              1001
#define IDC_DISCONNECT                  1002
#define IDC_DISCONNECT_BUTTON           1003
#define IDC_IP_ADDRESS                  1004
#define IDC_NETWORK_EDIT                1005
#define IDC_MAC_EDIT                    1006
#define IDC_NAME                        1007
#define IDC_MAC_EDIT2                   1007
#define IDC_GUID_EDIT                   1007
#define IDC_MANUFACTURER_EDIT           1008
#define IDC_NAME_EDIT                   1009
#define IDC_MODEL_EDIT                  1010
#define IDC_MAC_ADDRESS                 1011
#define IDC_NAME_EDIT2                  1012
#define IDC_DEVICE_EDIT                 1013
#define IDC_MAC_ADDRESS_NIC             1014
#define IDC_COMMUNICATION_MODE          1015
#define IDC_IP_EDIT                     1016
#define IDC_ACQUISITION_CONTROLS        1017
#define IDC_ACQUISITION_BUTTON          1018
#define IDC_DEVICE_PARAMETERS           1019
#define IDC_MODE                        1020
#define IDC_DEVICE_PARAMETERS2          1021
#define IDC_DEVICE_BUTTON               1022
#define IDC_CHANNEL                     1023
#define IDC_DEVICE_PARAMETERS3          1024
#define IDC_DEVICEEVENTS_BUTTON         1025
#define IDC_COMMUNICATION_BUTTON        1026
#define IDC_LINK_BUTTON                 1027
#define IDC_NUMBER_OF_FRAMES            1028
#define IDC_DEVICE_PARAMETERS4          1029
#define IDC_STREAMPARAMS_BUTTON         1030
#define IDC_DEVICE_PARAMETERS5          1031
#define IDC_STREAMSTATS_BUTTON          1032
#define IDC_START                       1033
#define IDC_STOP                        1034
#define IDC_RESET_BUTTON                1035
#define IDC_CLEAR_BUTTON                1036
#define IDC_CONTROL_GROUP               1037
#define IDC_SAVELOGBUTTON               1038
#define IDC_DISPLAY_GROUP               1039
#define IDC_DISPLAYPOS                  1040
#define IDC_CONTROL_GROUP2              1041
#define IDC_LOG_EDIT                    1042
#define IDC_STATUS                      1043
#define IDC_INFO                        1044
#define IDR_HTML                        1045
#define IDC_LISTBOX                     1046
#define IDC_LOGLISTBOX                  1047
#define IDC_PARAMETERS_GROUP            1048
#define IDC_LOG_GROUP                   1049
#define IDC_SELECTED_CHECK              1050
#define IDC_STATUS_D                    1051
#define IDC_BUTTON1                     1052
#define IDC_BUTTONSEND                  1052
#define ID_CANCEL                       1053
#define IDC_WBBUTTON                    1054
#define IDC_READBUTTON                  1055
#define IDB_WHEEL                       1056
#define IDC_BUTTON2                     1057
#define IDC_RESETBUTTON                 1058
#define IDC_WRITEBUTTON                 1059
#define IDC_AUTOCONFIGURE               1059
#define IDC_MULTICASTIP                 1060
#define IDC_CTRLDATA                    1061
#define IDC_CTRL                        1062
#define IDC_LIGHTSLIDER                 1062
#define IDC_DATA                        1063
#define IDC_DARKSLIDER                  1063
#define IDC_MONITOR                     1064
#define IDC_RGSLIDER                    1065
#define IDC_IP                          1066
#define IDC_GGSLIDER                    1067
#define IDC_BGSLIDER                    1068
#define IDC_ROSLIDER                    1069
#define IDC_GOSLIDER                    1070
#define IDC_BOSLIDER                    1071
#define IDC_BAYERCOMBO                  1072
#define IDC_MULTICASTPORT               1073
#define IDC_BAYERCOMBO2                 1073
#define IDC_TAPCOMBO                    1073
#define IDC_MULTICASTIPLABEL            1074
#define IDC_MULTICASTPORTLABEL          1075
#define IDC_IPLABEL                     1076
#define IDC_MULTICASTPORTLABEL2         1077
#define IDC_PORTLABEL                   1078
#define IDC_IPOS                        1078
#define IDC_PORT                        1079
#define IDC_UNICASTAUTO                 1080
#define IDC_UNICASTSPECIFIC             1081
#define IDC_UNICASTOTHER                1082
#define IDC_MULTICAST                   1083
#define IDC_ONEOUTOF_RADIO              1084
#define IDC_MAXRATE_RADIO               1085
#define IDC_SPECIFICPORTLABEL           1086
#define IDC_AVERAGETHROUGHPUT_RADIO     1087
#define IDC_SPECIFICPORT                1088
#define IDC_NOTHROTTLE_RADIO            1089
#define IDC_ONEOUTOF                    1090
#define IDC_MAXRATE                     1091
#define IDC_AVERAGETHROUGHPUT           1092
#define IDC_LOCATION                    1093
#define IDC_LOCATION_BUTTON             1094
#define IDC_CHECK1                      1095
#define IDC_SERIALCOMLOGENABLED         1095
#define IDC_SERIAL_COM_LOG_ENABLED      1095
#define IDC_DONT_SHOW_AGAIN             1095
#define IDC_CHECKSCHEDULED              1095
#define IDC_AVGBITRATE                  1095
#define IDC_ENABLEDCHECK                1096
#define IDC_CHECKREQUESTACKNOWLEDGES    1096
#define IDC_CHECKFORCEACKNOWLEDGEFLAG   1096
#define IDC_REQUESTACKNOWLEDGESCHECKBOX 1096
#define IDC_IMAGESAVEENABLE             1097
#define IDC_SAVELOGCHECKBOX             1098
#define IDC_HISTOGRAMENABLED            1098
#define IDC_BGEDIT                      1099
#define IDC_BGSPIN                      1100
#define IDC_RGEDIT                      1101
#define IDC_RGSPIN                      1102
#define IDC_GGEDIT                      1103
#define IDC_GGSPIN                      1104
#define IDC_ROEDIT                      1105
#define IDC_ROSPIN                      1106
#define IDC_BOEDIT                      1107
#define IDC_BOSPIN                      1108
#define IDC_GOEDIT                      1109
#define IDC_GOSPIN                      1110
#define IDC_GAINSLABEL                  1111
#define IDC_OFFSETSLABEL                1112
#define IDC_REDLABEL                    1113
#define IDC_GREENLABLE                  1114
#define IDC_GREENLABEL                  1115
#define IDC_BLUELABEL                   1116
#define IDC_LOCATIONGROUP               1117
#define IDC_THROTTLINGGROUP             1118
#define IDC_CAPTUREDIMAGESLABEL         1119
#define IDC_MSLABEL                     1120
#define IDC_AVERAGELABEL                1121
#define IDC_LOCATIONGROUP2              1122
#define IDC_FORMAT                      1123
#define IDC_READADDRESS                 1124
#define IDC_CAPTUREDIMAGESLABEL2        1124
#define IDC_LOCATIONGROUP3              1125
#define IDC_AVERAGELABEL2               1125
#define IDC_READVALUE                   1126
#define IDC_READRESULT                  1127
#define IDC_SAVELOGEDIT                 1128
#define IDC_4BUFFERS                    1129
#define IDC_WRITEADDRESS                1130
#define IDC_GENICAMCHECKBOX             1131
#define IDC_8BUFFERS                    1132
#define IDC_WRITEVALUE                  1133
#define IDC_BUFFERERRORCHECKBOX         1134
#define IDC_16BUFFERS                   1135
#define IDC_WRITERESULT                 1136
#define IDC_BUFFERALLCHECKBOX2          1137
#define IDC_BUFFERALLCHECKBOX           1138
#define IDC_32BUFFERS                   1139
#define IDC_64BUFFERS                   1140
#define IDC_128BUFFERS                  1141
#define IDC_64BUFFERS3                  1142
#define IDC_256BUFFERS                  1142
#define IDC_APPNAME                     1143
#define IDC_PRODUCTNAME                 1144
#define IDC_COPYRIGHT                   1145
#define IDC_COMPANY                     1146
#define IDC_SERIAL_COMMUNICATIONS_LABEL 1147
#define IDC_EDIT1                       1148
#define IDC_TEXTBOX                     1148
#define IDC_CHANNEL_EDIT                1148
#define IDC_BUFFERSIZE                  1148
#define IDC_EDITDEVICEKEY               1148
#define IDC_COMBO_INPUT                 1149
#define IDC_BUFFERSIZE2                 1149
#define IDC_BUFFERCOUNT                 1149
#define IDC_EDITGROUPMASK               1149
#define IDC_EDITGROUPKEY                1150
#define IDC_ACTIONTIME                  1151
#define IDC_CHANNEL_LABEL               1153
#define IDC_WARNING_MESSAGE             1154
#define IDC_LISTACK                     1157
#define IDC_STATIC_ACTIONTIME_ENABLED   1158
#define IDC_LIST_INTERFACES             1160
#define IDC_EVENTSCHECKBOX              1161
#define IDC_AUTOBUFFERRESIZINGCHECK     1163
#define IDC_AUTORESIZECHECK             1163
#define IDC_HELP1                       1164
#define IDC_HELP2                       1165
#define IDC_HELP3                       1166
#define IDC_FILECOMBO                   1167
#define IDC_DOWNLOADBUTTON              1168
#define IDC_PROGRESS1                   1169
#define IDC_PROGRESS                    1169
#define IDC_UPLOADBUTTON                1170
#define IDC_PROGRESSLABEL               1171
#define IDC_GROUP1                      1172
#define IDC_GROUP2                      1173
#define ID_FILE_EXIT                    32771
#define ID_FILE_SAVEDEVICECONFIGURATION 32772
#define ID_FILE_LOADDEVICECONFIGURATION 32773
#define ID_HELP_EVENTMONITOR            32774
#define ID_HELP_ABOUTEBUSPLAYER         32775
#define ID_Menu                         32776
#define ID_FILE_LOAD                    32777
#define ID_HELP_ABOUT                   32778
#define ID_TOOLS_DISPLAYIMAGES          32779
#define ID_TOOLS_AUTOMATICALLYURECONNECT 32780
#define ID_TOOLS_AUTOMATICALLYRECONNECT 32781
#define ID_TOOLS_OPTIONS                32782
#define ID_OPTIONS_AUTOMATICALLYRECONNECT 32783
#define ID_OPTIONS_DISPLAYIMAGES        32784
#define ID_FILE_OPENRECENT              32785
#define ID_FILE_SAVEAS                  32787
#define ID_FILE_RECENT1                 32788
#define ID_FILE_RECENT2                 32789
#define ID_FILE_RECENT3                 32790
#define ID_FILE_RECENT4                 32791
#define ID_FILE_RECENT5                 32792
#define ID_FILE_RECENT6                 32793
#define ID_FILE_RECENT7                 32794
#define ID_FILE_RECENT8                 32795
#define ID_FILE_RECENT9                 32796
#define ID_FILE_RECENT10                32797
#define ID_ACCELERATOR_SAVE             32798
#define ID_ACCELERATOR_OPEN             32799
#define ID_TOOLS_SETUP                  32801
#define ID_TOOLS_IMAGEFILTERING         32802
#define ID_TOOLS_SAVEIMAGES             32803
#define ID_TOOLS_SAVECURRENTIMAGE       32804
#define ID_TOOLS_IMAGESAVINGOPTIONS     32805
#define ID_TOOLS_DISPLAY                32807
#define ID_TOOLS_DISPLAYVSYNC           32808
#define ID_TOOLS_DIRECTREGISTERACCESS   32809
#define ID_TOOLS_REGISTER               32810
#define ID_REGISTERINTERFACE            32811
#define ID_TOOLS_BUFFERCOUNT            32813
#define ID_BUFFERCOUNT_4                32814
#define ID_BUFFERCOUNT_8                32815
#define ID_BUFFERCOUNT_16               32816
#define ID_BUFFERCOUNT_32               32817
#define ID_BUFFERCOUNT_64               32818
#define ID_BUFFERCOUNT_128              32819
#define ID_BUFFERCOUNT_256              32820
#define ID_DISPLAYIMAGES_DISABLED       32821
#define ID_DISPLAYIMAGES_30FPS          32822
#define ID_DISPLAYIMAGES_60FPS          32823
#define ID_TOOLS_BUFFERCOUNT32824       32824
#define ID_TOOLS_BUFFERCOUNT32825       32825
#define ID_TOOLS_SAVEPREFERENCES        32826
#define ID_TOOLS_RESTOREDEFAULTPREFERENCES 32827
#define ID_TOOLS_BUFFEROPTIONS          32828
#define ID_TOOLS_DISPLAYPARTIALIMAGES   32829
#define ID_TOOLS_SAVEXML                32830
#define ID_TOOLS_SAVE_XML               32831
#define ID_TOOLS_SERIALCOMMUNICATION    32832
#define ID_TOOLS_SERIALCOMMUNICATIONBRIDGE 32833
#define ID_TOOLS_EVENTMONITOR           32834
#define ID_TOOLS_DEINTERLACING          32835
#define ID_DEINTERLACING_DISABLED       32836
#define ID_DEINTERLACING_WEAVING        32837
#define ID_TOOLS_DEINTERLACING_DISABLED 32838
#define ID_TOOLS_DEINTERLACING_WEAVING  32839
#define ID_TOOLS_ACTIONCOMMAND          32840
#define ID_TOOLS_DISPLAYCHUNKDATA       32841
#define ID_TOOLS_DISPLAYCHUNK_DATA      32842
#define ID_TOOLS_DISPLAY_CHUNK_DATA     32843
#define ID_TOOLS_DEVICESERIALCOMMUNICATION 32844
#define ID_TOOLS_DEFAULTGIGEVISIONCOMMUNICATIONPARAMETERS 32845
#define ID_TOOLS_DEFAULTUSB3VISIONCOMMUNICATIONPARAMETERS 32846
#define ID_TOOLS_DEFAULTGEVCOMMUNICATIONPARAMETERS 32847
#define ID_TOOLS_DEFAULTU3VCOMMUNICATIONPARAMETERS 32848
#define ID_TOOLS_UPLOADTODEVICE         32849
#define ID_TOOLS_UPLOADTODEVICE32850    32850
#define ID_TOOLS_DOWNLOADFROMDEVICE     32851
#define ID_TOOLS_UPLOADFILETODEVICE     32852
#define ID_TOOLS_DOWNLOADFILEFROMDEVICE 32853
#define ID_TOOLS_FILETRANSFER           32854
#define ID_DEINTERLACING_WEAVEFULLTEMPORALRESOLUTION 32855
#define ID_DEINTERLACING_BLENDING       32856
#define ID_DEINTERLACING_LINEDOUBLING   32857
#define ID_TOOLS_DEINTERLACING_WEAVE_HALF 32858
#define ID_TOOLS_DEINTERLACING_WEAVE_FULL 32859
#define ID_TOOLS_DEINTERLACING_BLENDING 32860
#define ID_TOOLS_DEINTERLACING_LINEDOUBLING 32861
#define ID_TOOLS_RESETSTREAMINGSTATISTICS 32862
#define ID_TOOLS_RESET_STREAMING_STATISTICS 32863

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32864
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
